routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'Dashboard')->name('dashboard');

    Route::resource('locations', 'LocationController');
    Route::resource('manufacturers', 'ManufacturerController');
    Route::resource('notes', 'NoteController');
    Route::resource('products', 'ProductController');
    Route::resource('stocks', 'StockController');
});

Auth::routes();

app/Location.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Kalnoy\Nestedset\NodeTrait;

class Location extends Model
{
    use NodeTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'parent_id' => 'integer'
    ];
}

app/Http/Controllers/LocationController.php
<?php

namespace App\Http\Controllers;

use App\Location;
use App\Http\Requests\StoreLocation;
use App\Http\Requests\UpdateLocation;
use Illuminate\Http\Request;

class LocationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Only return root level locations on the index page.
        $locations = Location::whereIsRoot()->get();

        // Show the locations index.
        return view('resources.locations.index', compact('locations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        // Retrieve all the locations for the parent dropdown.
        // TODO: Probably have to replace this with an ajax search later on.
        $locations = Location::orderBy('name')->get(); 

        // Check if there is a parent defined in the request.
        $parent = $request->get('parent', false);

        // Show the location creation form.
        return view('resources.locations.create', compact('locations', 'parent'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreLocation $request)
    {
        // Retrieve the validated data from StoreLocation.
        $validated = $request->validated();

        // Create the location with the validated data.
        $location = Location::create($validated);
        
        // Seperate the parent ID from the request.
        $parent = $request->get('parent_id');
        
        // If there is a parent it needs to be added as a node, otherwise it needs to be saved as a root.
        if($parent > 0) {
            $parent = Location::findOrFail($parent);
            $location->appendToNode($parent)->save();
        } else {
            $location->saveAsRoot();
        }

        // Return to the locations index with a success message.
        return redirect()->route('locations.index')->with('success', 'Location is successfully saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Location  $location
     * @return \Illuminate\Http\Response
     */
    public function show(Location $location)
    {
        // Retrieve all the descendants of the shown location.
        $sublocations = Location::whereDescendantOf($location)->where('parent_id', '=', $location->id)->get();

        // Show the location.
        return view('resources.locations.show', compact('location', 'sublocations'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Location  $location
     * @return \Illuminate\Http\Response
     */
    public function edit(Location $location)
    {
        // Retrieve all the locations for the parent dropdown.
        $locations = Location::orderBy('name')->get();

        // Show the location edit form.
        return view('resources.locations.edit', compact('location', 'locations'));  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Location  $location
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateLocation $request, Location $location)
    {
        // Retrieve the validated data from UpdateLocation.
        $validated = $request->validated();
        
        // Update the location with the validated data.
        Location::whereId($location->id)->update($validated);

        // Seperate the parent ID from the request.
        $parent = $request->get('parent_id');

        // If there is a parent it needs to be added as a node, otherwise it needs to be saved as a root.
        if($parent > 0) {
            $parent = Location::findOrFail($parent);
            $location->appendToNode($parent)->save();
        } else {
            $location->saveAsRoot();
        }
        
        // Return to the locations index with a success message.
        return redirect()->route('locations.index')->with('success', 'Location is successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Location  $location
     * @return \Illuminate\Http\Response
     */
    public function destroy(Location $location)
    {
        // Delete the location.
        $location->delete();

        // Return to the locations index with a success message.
        return redirect()->route('locations.index')->with('success', 'Location is successfully deleted!');
    }
}

resources/views/resources/locations/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10 col-xl-8">
            <!-- Header -->
            <div class="header mb-4">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="mb-1">Create</h6>
                            <h1 class="mb-0">Location</h1>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Header -->

            <hr />

            <!-- Form -->
            <form method="post" action="{{ route('locations.store') }}">
                @csrf
                <div class="form-group">
                    <label for="name">Location name</label>
                    <input type="text" class="form-control" name="name" id="name">
                </div>
                <div class="form-group">
                    <label for="parent_id">Location parent</label>
                    <select class="custom-select" name="parent_id" id="parent_id">
                        <option value="0" selected>No parent</option>
                        @foreach($locations as $location)
                            @if($parent == $location->id)
                                <option value="{{ $location->id }}" selected>{{ $location->name }}</option>
                            @else
                                <option value="{{ $location->id }}">{{ $location->name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <hr />
                <button type="submit" class="btn btn-primary btn-block">Create Location</button>
            </form>
            <!-- /Form -->
        </div>
    </div>
</div>
@endsection

resources/views/resources/locations/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10 col-xl-8">
            <!-- Header -->
            <div class="header mb-4">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="mb-1">Edit Location</h6>
                            <h1 class="mb-0">{{ $location->name }}</h1>
                        </div>
                        <form method="post" action="{{ route('locations.destroy', $location->id) }}" class="col-auto">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /Header -->

            <hr />

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <!-- Form -->
            <form method="post" action="{{ route('locations.update', $location->id) }}">
                @method('PATCH') 
                @csrf
                <div class="form-group">
                    <label for="name">Location name</label>
                    <input type="text" class="form-control" name="name" id="name" value="{{ $location->name }}">
                </div>
                <div class="form-group">
                    <label for="parent_id">Location parent</label>
                    <select class="custom-select" name="parent_id" id="parent_id">
                        <option value="0" selected>No parent</option>
                        @foreach($locations as $location_p)
                            @if($location->parent_id == $location_p->id)
                                <option value="{{ $location_p->id }}" selected>{{ $location_p->name }}</option>
                            @else
                                <option value="{{ $location_p->id }}">{{ $location_p->name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <hr />
                <button type="submit" class="btn btn-primary btn-block">Update Location</button>
            </form>
            <!-- /Form -->
        </div>
    </div>
</div>
@endsection

resources/views/resources/locations/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12">
            <!-- Header -->
            <div class="header mb-4">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="mb-1">Overview</h6>
                            <h1 class="mb-0">Locations</h1>
                        </div>
                        <div class="col-auto">
                            <a href="{{ route('locations.create') }}" class="btn btn-primary">New Location</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Header -->

            @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}  
                </div>
            @endif

            <!-- Card -->
            <div class="card">
                {{-- <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <form class="input-group">
                                <input type="search" class="form-control form-control-flush" placeholder="Search Location" aria-label="Search Location" aria-describedby="button-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="button" id="button-addon2">Search</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div> --}}

                <div class="table-responsive">
                    <table class="table table-nowrap card-table table-hover mb-0">
                        <thead>
                            <tr>
                                <th class="border-0"><a href="#" class="text-muted sort">Name</a></th>
                                <th class="border-0"><a href="#" class="text-muted sort">Sub Locations</a></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($locations as $location)
                                <tr>
                                    <td><a href="{{ route('locations.show', $location->id)}}">{{ $location->name }}</a></td>
                                    <td>{{ $location->descendants->count() }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /Card -->
        </div>
    </div>
</div>
@endsection

resources/views/resources/locations/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12">
            <!-- Header -->
            <div class="header mb-4">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="mb-1">View Location</h6>
                            <h1 class="mb-0">{{ $location->name }}</h1>
                        </div>
                        <div class="col-auto">
                            <a href="{{ route('locations.create', ['parent' => $location->id]) }}" class="btn btn-primary">New Sub Location</a>
                            <a href="{{ route('locations.edit', $location->id) }}" class="btn btn-secondary">Edit Location</a>
                        </div>
                    </div>
                    <div class="row align-items-center mt-2">
                        <div class="col">
                            <ul class="nav nav-tabs nav-overflow header-tabs">
                                <li class="nav-item">
                                    <a href="#" class="nav-link active">Sub Locations</a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">Stock</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Header -->

            <!-- Card -->
            <div class="card">
                <div class="table-responsive">
                    <table class="table table-nowrap card-table table-hover mb-0">
                        <thead>
                            <tr>
                                <th class="border-0"><a href="#" class="text-muted sort">Name</a></th>
                                <th class="border-0"><a href="#" class="text-muted sort">Sub Locations</a></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($sublocations as $sublocation)
                                <tr>
                                    <td><a href="{{ route('locations.show', $sublocation->id)}}">{{ $sublocation->name }}</a></td>
                                    <td>{{ $sublocation->descendants->count() }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /Card -->
        </div>
    </div>
</div>
@endsection