routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'Dashboard')->name('dashboard');

    Route::resource('locations', 'LocationController');
    Route::resource('manufacturers', 'ManufacturerController');
    Route::resource('notes', 'NoteController');
    Route::resource('products', 'ProductController');
    Route::resource('stocks', 'StockController');
});

Auth::routes();

app/Manufacturer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Manufacturer extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 
        'url', 
        'image'
    ];

    public function products()
    {
        return $this->hasMany('App\Product', 'manufacturer_id', 'id');
    }
}

app/Http/Controllers/ManufacturerController.php
<?php

namespace App\Http\Controllers;

use App\Manufacturer;
use App\Http\Requests\StoreManufacturer;
use App\Http\Requests\UpdateManufacturer;
use Illuminate\Http\Request;

class ManufacturerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Return all manufacturers.
        $manufacturers = Manufacturer::orderBy('name')->get(); 

        // Show the manufacturers index.
        return view('resources.manufacturers.index', compact('manufacturers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Show the manufacturer creation form.
        return view('resources.manufacturers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreManufacturer $request)
    {
        // Retrieve the validated data from StoreManufacturer.
        $validated = $request->validated();

        // Create the manufacturer with the validated data.
        Manufacturer::create($validated);
        
        // Return to the manufacturers index with a success message.
        return redirect()->route('manufacturers.index')->with('success', 'Manufacturer is successfully saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Manufacturer  $manufacturer
     * @return \Illuminate\Http\Response
     */
    public function show(Manufacturer $manufacturer)
    {
        // Show the manufacturer.
        return view('resources.manufacturers.show', compact('manufacturer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Manufacturer  $manufacturer
     * @return \Illuminate\Http\Response
     */
    public function edit(Manufacturer $manufacturer)
    {
        // Show the manufacturer edit form.
        return view('resources.manufacturers.edit', compact('manufacturer'));   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Manufacturer  $manufacturer
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateManufacturer $request, Manufacturer $manufacturer)
    {
        // Retrieve the validated data from UpdateManufacturer.
        $validated = $request->validated();

        // Update the manufacturer with the validated data.
        Manufacturer::whereId($manufacturer->id)->update($validated);

        // Return to the manufacturers index with a success message.
        return redirect()->route('manufacturers.index')->with('success', 'Manufacturer is successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Manufacturer  $manufacturer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Manufacturer $manufacturer)
    {
        // Delete the manufacturer.
        $manufacturer->delete();

        // Return to the manufacturers index with a success message.
        return redirect()->route('manufacturers.index')->with('success', 'Manufacturer is successfully deleted!');
    }
}

resources/views/resources/manufacturers/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10 col-xl-8">
            <!-- Header -->
            <div class="header mb-4">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="mb-1">Create</h6>
                            <h1 class="mb-0">Manufacturer</h1>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Header -->

            <hr />

            <!-- Form -->
            <form method="post" action="{{ route('manufacturers.store') }}">
                @csrf
                <div class="form-group">
                    <label for="name">Manufacturer name</label>
                    <input type="text" class="form-control" name="name" id="name">
                </div>
                <div class="form-group">
                    <label for="url">Manufacturer website</label>
                    <input type="text" class="form-control" name="url" id="url">
                </div>
                <div class="form-group">
                    <label for="image" id="image-description">Manufacturer logo</label>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="image" aria-describedby="image-description">
                        <label class="custom-file-label" for="image">Choose file</label>
                    </div>
                </div>
                <hr />
                <button type="submit" class="btn btn-primary btn-block">Create Manufacturer</button>
            </form>
            <!-- /Form -->
        </div>
    </div>
</div>
@endsection

resources/views/resources/manufacturers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10 col-xl-8">
            <!-- Header -->
            <div class="header mb-4">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="mb-1">Edit Manufacturer</h6>
                            <h1 class="mb-0">{{ $manufacturer->name }}</h1>
                        </div>
                        <form method="post" action="{{ route('manufacturers.destroy', $manufacturer->id) }}" class="col-auto">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /Header -->

            <hr />

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <!-- Form -->
            <form method="post" action="{{ route('manufacturers.update', $manufacturer->id) }}">
                @method('PATCH') 
                @csrf
                <div class="form-group">
                    <label for="name">Manufacturer name</label>
                    <input type="text" class="form-control" name="name" id="name" value="{{ $manufacturer->name }}">
                </div>
                <div class="form-group">
                    <label for="url">Manufacturer website</label>
                    <input type="text" class="form-control" name="url" id="url" value="{{ $manufacturer->url }}">
                </div>
                <div class="form-group">
                    <label for="image" id="image-description">Manufacturer logo</label>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="image" aria-describedby="image-description">
                        <label class="custom-file-label" for="image">Choose file</label>
                    </div>
                </div>
                <hr />
                <button type="submit" class="btn btn-primary btn-block">Update Manufacturer</button>
            </form>
            <!-- /Form -->
        </div>
    </div>
</div>
@endsection

resources/views/resources/manufacturers/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12">
            <!-- Header -->
            <div class="header mb-4">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="mb-1">Overview</h6>
                            <h1 class="mb-0">Manufacturers</h1>
                        </div>
                        <div class="col-auto">
                            <a href="{{ route('manufacturers.create') }}" class="btn btn-primary">New Manufacturer</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Header -->

            @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}  
                </div>
            @endif

            <!-- Card -->
            <div class="card">
                <div class="table-responsive">
                    <table class="table table-nowrap card-table table-hover mb-0">
                        <thead>
                            <tr>
                                <th class="border-0" width="40%"><a href="#" class="text-muted sort">Name</a></th>
                                <th class="border-0" width="40%"><a href="#" class="text-muted sort">Website</a></th>
                                <th class="border-0"><a href="#" class="text-muted sort">Products</a></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($manufacturers as $manufacturer)
                                <tr>
                                    <td><a href="{{ route('manufacturers.show', $manufacturer->id)}}">{{ $manufacturer->name }}</a></td>
                                    <td><a href="{{ $manufacturer->url }}" target="blank">Website</a></td>
                                    <td>-</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /Card -->
        </div>
    </div>
</div>
@endsection

resources/views/resources/manufacturers/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12">
            <!-- Header -->
            <div class="header mb-4">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="mb-1">View Manufacturer</h6>
                            <h1 class="mb-0">{{ $manufacturer->name }}</h1>
                        </div>
                        <div class="col-auto">
                            <a href="{{ route('manufacturers.edit', $manufacturer->id) }}" class="btn btn-primary">Edit Manufacturer</a>
                        </div>
                    </div>
                    <div class="row align-items-center mt-2">
                        <div class="col">
                            <ul class="nav nav-tabs nav-overflow header-tabs">
                                <li class="nav-item">
                                    <a href="#" class="nav-link active">Products</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ $manufacturer->url }}" target="_blank" class="nav-link">Manufacturer Website</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Header -->

            <!-- Card -->
            <div class="card">
                @if ( ! empty( $manufacturer->products ) )
                    <div class="table-responsive">
                        <table class="table table-nowrap card-table table-hover mb-0">
                            <thead>
                                <tr>
                                    <th class="border-0"><a href="#" class="text-muted sort">Name</a></th>
                                    <th class="border-0"><a href="#" class="text-muted sort">Stock</a></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($manufacturer->products as $product)
                                    <tr>
                                        <td><a href="{{ route('products.show', $product->id) }}">{{ $product->name }}</a></td>
                                        <td>-</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                     <div class="card-body">
                        <p class="mb-0">No products have been added to this manufacturer.</p>
                     </div>
                @endif
            </div>
            <!-- /Card -->
        </div>
    </div>
</div>
@endsection