routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'Dashboard')->name('dashboard');

    Route::resource('locations', 'LocationController');
    Route::resource('manufacturers', 'ManufacturerController');
    Route::resource('notes', 'NoteController');
    Route::resource('products', 'ProductController');
    Route::resource('stocks', 'StockController');
});

Auth::routes();

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 
        'gtin', 
        'weight',
        'manufacturer_id'
    ];

    public function manufacturer()
    {
        return $this->belongsTo('App\Manufacturer', 'manufacturer_id', 'id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Manufacturer;
use App\Http\Requests\StoreProduct;
use App\Http\Requests\UpdateProduct;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Return all products.
        $products = Product::all(); 

        // Show the products index.
        return view('resources.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Retrieve all the manufacturers for the dropdown.
        // TODO: Probably have to replace this with an ajax search later on.
        $manufacturers = Manufacturer::orderBy('name')->get(); 

        // Show the product creation form.
        return view('resources.products.create', compact('manufacturers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProduct $request)
    {
        // Retrieve the validated data from StoreProduct.
        $validated = $request->validated();

        // Create the product with the validated data.
        Product::create($validated);
        
        // Return to the products index with a success message.
        return redirect()->route('products.index')->with('success', 'Product is successfully saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        // Show the product.
        return view('resources.products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        // Retrieve all the manufacturers for the dropdown.
        $manufacturers = Manufacturer::orderBy('name')->get(); 

        // Show the product edit form.
        return view('resources.products.edit', compact('product', 'manufacturers'));   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProduct $request, Product $product)
    {
        // Retrieve the validated data from UpdateProduct.
        $validated = $request->validated();

        // Update the product with the validated data.
        Product::whereId($product->id)->update($validated);
        
        // Return to the products index with a success message.
        return redirect()->route('products.index')->with('success', 'Product is successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        // Delete the product.
        $product->delete();

        // Return to the products index with a success message.
        return redirect()->route('products.index')->with('success', 'Product is successfully deleted!');
    }
}

resources/views/resources/products/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10 col-xl-8">
            <!-- Header -->
            <div class="header mb-4">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="mb-1">Create</h6>
                            <h1 class="mb-0">Product</h1>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Header -->

            <hr />

            <!-- Form -->
            <form method="post" action="{{ route('products.store') }}">
                @csrf
                <div class="form-group">
                    <label for="name">Product name</label>
                    <input type="text" class="form-control" name="name" id="name">
                </div>
                <div class="form-group">
                    <label for="manufacturer_id">Product manufacturer</label>
                    <select class="custom-select" name="manufacturer_id" id="manufacturer_id">
                        @foreach($manufacturers as $manufacturer)
                            <option value="{{ $manufacturer->id }}">{{ $manufacturer->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="gtin">Product GTIN</label>
                    <input type="text" class="form-control" name="gtin" id="gtin">
                </div>
                <div class="form-group">
                    <label for="weight">Product Weight</label>
                    <input type="text" class="form-control" name="weight" id="weight">
                </div>
                <hr />
                <button type="submit" class="btn btn-primary btn-block">Create Product</button>
            </form>
            <!-- /Form -->
        </div>
    </div>
</div>
@endsection

resources/views/resources/products/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10 col-xl-8">
            <!-- Header -->
            <div class="header mb-4">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="mb-1">Edit Product</h6>
                            <h1 class="mb-0">{{ $product->name }}</h1>
                        </div>
                        <form method="post" action="{{ route('products.destroy', $product->id) }}" class="col-auto">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /Header -->

            <hr />

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <!-- Form -->
            <form method="post" action="{{ route('products.update', $product->id) }}">
                @method('PATCH') 
                @csrf
                <div class="form-group">
                    <label for="name">Product name</label>
                    <input type="text" class="form-control" name="name" id="name" value="{{ $product->name }}">
                </div>
                <div class="form-group">
                    <label for="manufacturer_id">Product manufacturer</label>
                    <select class="custom-select" name="manufacturer_id" id="manufacturer_id">
                        @foreach($manufacturers as $manufacturer)
                            @if($manufacturer->id == $product->manufacturer_id)
                                <option value="{{ $manufacturer->id }}" selected>{{ $manufacturer->name }}</option>
                            @else
                                <option value="{{ $manufacturer->id }}">{{ $manufacturer->name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="gtin">Product GTIN</label>
                    <input type="text" class="form-control" name="gtin" id="gtin" value="{{ $product->gtin }}">
                </div>
                <div class="form-group">
                    <label for="weight">Product Weight</label>
                    <input type="text" class="form-control" name="weight" id="weight" value="{{ $product->weight }}">
                </div>
                <hr />
                <button type="submit" class="btn btn-primary btn-block">Update Product</button>
            </form>
            <!-- /Form -->
        </div>
    </div>
</div>
@endsection

resources/views/resources/products/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12">
            <!-- Header -->
            <div class="header mb-4">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="mb-1">Overview</h6>
                            <h1 class="mb-0">Products</h1>
                        </div>
                        <div class="col-auto">
                            <a href="{{ route('products.create') }}" class="btn btn-primary">New Product</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Header -->

            @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}  
                </div>
            @endif

            <!-- Card -->
            <div class="card">
                <div class="table-responsive">
                    <table class="table table-nowrap card-table table-hover mb-0">
                        <thead>
                            <tr>
                                <th class="border-0" width="40%"><a href="#" class="text-muted sort">Name</a></th>
                                <th class="border-0" width="40%"><a href="#" class="text-muted sort">Manufacturer</a></th>
                                <th class="border-0"><a href="#" class="text-muted sort">Stock</a></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($products as $product)
                                <tr>
                                    <td><a href="{{ route('products.show', $product->id) }}">{{ $product->name }}</a></td>
                                    @if (!empty($product->manufacturer))
                                        <td><a href="{{ route('manufacturers.show', $product->manufacturer->id) }}">{{ $product->manufacturer->name }}</a></td>
                                    @else
                                        <td>No manufacturer</td>
                                    @endif
                                    <td>-</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /Card -->
        </div>
    </div>
</div>
@endsection

resources/views/resources/products/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12">
            <!-- Header -->
            <div class="header mb-4">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="mb-1">View Product</h6>
                            <h1 class="mb-0">{{ $product->name }}</h1>
                        </div>
                        <div class="col-auto">
                            <a href="{{ route('products.edit', $product->id) }}" class="btn btn-primary">Edit Product</a>
                        </div>
                    </div>
                    <div class="row align-items-center mt-2">
                        <div class="col">
                            <ul class="nav nav-tabs nav-overflow header-tabs">
                                <li class="nav-item">
                                    <a href="#" class="nav-link active">Stock</a>
                                </li>
                                @if (!empty($product->manufacturer))
                                    <li class="nav-item">
                                        <a href="{{ route('manufacturers.show', $product->manufacturer->id) }}" class="nav-link">Manufacturer</a>
                                    </li>
                                @endif
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Header -->

            <!-- Card -->
            <div class="card">
                <div class="table-responsive">
                    <table class="table table-nowrap card-table table-hover mb-0">
                        <thead>
                            <tr>
                                <th class="border-0"><a href="#" class="text-muted sort">Location</a></th>
                                <th class="border-0"><a href="#" class="text-muted sort">Stock</a></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>-</td>
                                <td>-</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /Card -->
        </div>
    </div>
</div>
@endsection